apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: dev
data:
  initdb.sql: |
    # create databases
    CREATE DATABASE IF NOT EXISTS `employee`;
    CREATE DATABASE IF NOT EXISTS `department`;

    # create user and grant rights
    GRANT ALL PRIVILEGES ON *.* TO $MYSQL_USER@'%' WITH GRANT OPTION;