apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: eureka
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
            limits:
              cpu: "250m"
              memory: "200Mi"