apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
      version: 1.0.0
  template:
    metadata:
      labels:
        app: eureka
        version: 1.0.0