apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
      version: 1.0.0
  template:
    metadata:
      name: employee
      labels:
        app: employee
        version: 1.0.0
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: api-configmap
      # restartPolicy: Never
      containers:
        - name: employee
          image: cabrelkemfang/employee-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: employee-port
          resources:
            requests:
              cpu: "200m"
              memory: "0.5Gi"
            limits:
              memory: "1Gi"
          # livenessProbe:
          #   httpGet:
          #     port: employee-port
          #     path: /api/actuator/health/liveness
          #   failureThreshold: 4
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 50
          # readinessProbe:
          #   httpGet:
          #     port: employee-port
          #     path: /api/actuator/health/readiness
          #   failureThreshold: 4
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 50
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["sh", "-c", "sleep 10"]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
          env:
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  key: JDBC_URL
                  name: api-configmap
            - name: DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: DRIVER_CLASS_NAME
                  name: api-configmap
            - name: JPA_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: JPA_DIALECT
                  name: api-configmap
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: api-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: api-secret