apiVersion: v1
kind: Service
metadata:
  name: employee-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: dev
spec:
  selector:
    app: employee
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP