apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: api-configmap
data:
  DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  JPA_DIALECT: "org.hibernate.dialect.MySQLDialect"
  EUREKA_SERVER: "http://eureka-deployment-0.eureka-sevice:8761/eureka"
  ZIPKIN_URL: "http://localhost:30000/api/v2/spans"
  JDBC_URL: "jdbc:mysql://mysql/employee?allowPublicKeyRetrieval=true"