apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: zipkin
    version: latest
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30000
  type: NodePort