apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zipkin
      version: latest
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
        version: latest