apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: employee
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
            limits:
              memory: "250m"
              cpu: "200Mi"