apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
      version: 1.0.0
  template:
    metadata:
      name: employee
      labels:
        app: employee
        version: 1.0.0