# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - ../../../../base/argoCd

# patches:
# - path: agrocd-application-patch.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agrocd-application-patch.yaml