apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: io.growtogether
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cabrelkemfang/k8s-manifest.git'
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
