apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: 1.0.0
  template:
    metadata:
      labels:
        app: api-gateway
        version: 1.0.0
    spec:
      containers:
        - name: api-gateway
          image: cabrelkemfang/api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
              name: employee-port
            - containerPort: 9195
              name: actuator-port
          env:
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  key: ZIPKIN_URL
                  name: api-configmap
          resources:
            requests:
              cpu: "1000m"
              memory: "0.5Gi"
            limits:
              memory: "0.5Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              port: actuator-port
              path: /actuator/health/liveness
            failureThreshold: 4
            periodSeconds: 5
            timeoutSeconds: 50
          readinessProbe:
            httpGet:
              port: actuator-port
              path: /actuator/health/readiness
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 60
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      restartPolicy: Always