apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: 1.0.0
  template:
    metadata:
      labels:
        app: api-gateway
        version: 1.0.0
    spec:
      containers:
        - name: api-gateway
          image: cabrelkemfang/api-gateway:1.0.0
          imagePullPolicy: Always
          env:
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  key: ZIPKIN_URL
                  name: api-configmap
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_SERVER
                  name: api-configmap
          resources:
            requests:
              cpu: "1000m"
              memory: "0.5Gi"
            limits:
              memory: "0.5Gi"
              cpu: "1000m"
      restartPolicy: Always