apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: api-gateway
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8060
  type: LoadBalancer