
apiVersion: v1
kind: Service
metadata:
  name: eureka-sevice
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: eureka
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8761
  clusterIP: None