# apiVersion: v1
# kind: Service
# metadata:
#  name: mysql-svc
# spec:
#   clusterIP: None
#   ports:
#   - port: 3306

# ---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  clusterIP: None
  ports:
  - port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql
subsets:
  - addresses:
        - ip: 34.41.119.5
    ports:
      - port: 3306