apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
      version: 1.0.0
  template:
    metadata:
      labels:
        app: api-gateway
        version: 1.0.0