apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: api-configmap
data:
  DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  JPA_DIALECT: "org.hibernate.dialect.MySQLDialect"
  EUREKA_SERVER: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
  ZIPKIN_URL: "http://localhost:30000/api/v2/spans"
  JDBC_URL: "jdbc:mysql://mysql:3306/employee"