apiVersion: v1
kind: Service
metadata:
  name: department
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: dev
spec:
  selector:
    app: department
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: dev
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
      version: 1.0.0
  template:
    metadata:
      name: department
      labels:
        app: department
        version: 1.0.0
    spec:
      containers:
        - name: department
          image: cabrelkemfang/department-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: department-port
          resources:
            requests:
              cpu: "200m"
              memory: "0.5Gi"
            limits:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              port: department-port
              path: /api/v1/actuator/health/liveness
            failureThreshold: 4
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 50
          readinessProbe:
            httpGet:
              port: department-port
              path: /api/v1/actuator/health/readiness
            failureThreshold: 4
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 50
          env:
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  key: JDBC_DEPARTMENT_URL
                  name: api-configmap
            - name: DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: DRIVER_CLASS_NAME
                  name: api-configmap
            - name: JPA_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: JPA_DIALECT
                  name: api-configmap
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql_user
                  name: api-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: api-secret