apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  mysql_root_password: bXlzcWxAMjM3Cg==
  mysql_admin_password: bXlzcWxAMjM3Cg==
  mysql_user: ""