apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: zipkin
    version: latest
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: dev
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
      version: latest
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
        version: latest
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            failureThreshold: 5
            httpGet:
              port: zipkin-port
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 20
          livenessProbe:
            failureThreshold: 5
            httpGet:
              port: zipkin-port
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 20
          resources:
            requests:
              cpu: "1000m"
              memory: "0.5Gi"
            limits:
              memory: "0.5Gi"
              cpu: "1000m"
          ports:
            - containerPort: 9411
              name: zipkin-port
      restartPolicy: Always